spring:
  application:
    name: contact-aggregator
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

kenect:
  api:
    base-url: ${KENECT_BASE_URL:https://k-messages-api.herokuapp.com/api/v1}
    auth-token: ${KENECT_TOKEN_API:<TOKEN_API>}

logging:
  level:
    org.springframework: ${KENECT_LOGGING_LEVEL:INFO}